# Generated by Django 5.2.18 on 2026-10-08 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(default='#17375e', help_text='Cor hexadecimal usada na arte sem foto, ex.: #F2B544.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use o formato #RRGGBB.')], verbose_name='cor da arte'),
        ),
        migrations.AddField(
            model_name='produto',
            name='num_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('saco', 'Saco'), ('lata', 'Lata'), ('frasco', 'Frasco'), ('bola', 'Bola'), ('osso', 'Osso'), ('caixa', 'Caixa'), ('cama', 'Cama'), ('coleira', 'Coleira'), ('pote', 'Pote')], default='caixa', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja.departamento'),
        ),
    ]
