# Generated by Django 5.2.18 on 2026-10-08 21:01

from django.db import migrations, models

from loja.texto import normalizar


def preencher_texto_busca(apps, schema_editor):
    Produto = apps.get_model("loja", "Produto")
    for produto in Produto.objects.all():
        texto = normalizar(f"{produto.nome} {produto.marca} {produto.descricao}")
        Produto.objects.filter(pk=produto.pk).update(texto_busca=texto)


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='texto_busca',
            field=models.TextField(default='', editable=False),
        ),
        migrations.RunPython(preencher_texto_busca, migrations.RunPython.noop),
    ]
