# Generated by Django 5.2.18 on 2026-10-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_produto_texto_busca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartamentos', to='loja.departamento')),
            ],
            options={
                'verbose_name': 'subdepartamento',
                'ordering': ['departamento__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='subdepartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja.subdepartamento'),
        ),
    ]
