# Generated by Django 5.2.18 on 2026-10-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_subdepartamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subdepartamento',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='subdepartamento',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Subdepartamento',
        ),
    ]
